name: CI Pipeline
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code 
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependencies 
        working-directory: backend
        run: pip install -r requirements.txt

      - name: runt pytest 
        working-directory: backend
        run: pytest 

      - name: install bandit
        run: pip install bandit 

      - name: run bandit against backend
        working-directory: backend
        run: bandit -r 
